### ISSUE TITLE
Аргументы в Payment

### ISSUE THREAD

**Issue by almightyprometej** [evotor/evotor-api-example#4]
неясно с четвертым аргументом
W/System.err: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter paymentPerformer
и параметр paymentPerformer не может быть null

как вписать оплату картой? new PaymentPerformer(????),

**Comment by almightyprometej** [comment]
Обратите внимание на исходники [https://github.com/evotor/integration-library/blob/develop/src/main/java/ru/evotor/framework/receipt/Payment.kt](https://github.com/evotor/integration-library/blob/develop/src/main/java/ru/evotor/framework/receipt/Payment.kt)
Для начала необходимо создать экземпляр класса PaymentPerformer

```
PaymentPerformer paymentPerformer = new PaymentPerformer(
 new PaymentSystem(
 PaymentType.CASH,
 "описание",
 "название платежной системы"),
 "имя пакета",
 "название компонента",
 "app_uuid",
 "название приложения");
```

а затем, формируя 

`HashMap<Payment, BigDecimal>`

поместить в нее 

```
new Payment(UUID.randomUUID().toString(),
 сумма,
        null,
 paymentPerformer,
        null,
        null,
 "описание"),
 сумма);
```

**Comment by hopyres** [comment]
```
public class DiscountService extends IntegrationService {
  @Nullable
  @Override
  protected Map<String, ActionProcessor> createProcessors() {
    Intent intent = new Intent(this, DiscountActivity.class);
    startActivity(intent);
    return null;
  }
}
```
Как нужно правильно вызвать Activity, чтобы приложение не падало?
